import { Router } from "express";
import { authRouter } from "./auth.routes.js";
import { usersRouter } from "./users.routes.js";
import { discoveryRouter } from "./discovery.routes.js";
import { companiesRouter } from "./companies.routes.js";
import { leadsRouter } from "./leads.routes.js";
import { emailsRouter } from "./emails.routes.js";
import { approvalQueueRouter } from "./approvalQueue.routes.js";
import { campaignsRouter } from "./campaigns.routes.js";
import { analyticsRouter } from "./analytics.routes.js";
import { copilotRouter } from "./copilot.routes.js";
import { webhooksRouter } from "./webhooks.routes.js";
import { internalRouter } from "./internal.routes.js";
import { notificationsRouter } from "./notifications.routes.js";
import { auditRouter } from "./audit.routes.js";
import { similarityRouter } from "./similarity.routes.js";
import { discoveredLeadsRouter } from "./discoveredLeads.routes.js";
import { aiUsageRouter } from "./aiUsage.routes.js";
import { nurturingRouter } from "./nurturing.routes.js";
import { organizationsRouter } from "./organizations.routes.js";
import { tenantsRouter } from "./tenants.routes.js";
import { publicRouter } from "./public.routes.js";
import { userSettingsRouter } from "./userSettings.routes.js";
import { knowledgeBaseRouter } from "./knowledgeBase.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/users", userSettingsRouter);
apiRouter.use("/discovery", discoveryRouter);
apiRouter.use("/companies", companiesRouter);
apiRouter.use("/leads", leadsRouter);
apiRouter.use("/emails", emailsRouter);
apiRouter.use("/approval-queue", approvalQueueRouter);
apiRouter.use("/campaigns", campaignsRouter);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/copilot", copilotRouter);
apiRouter.use("/webhooks", webhooksRouter);
apiRouter.use("/internal", internalRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/similarity", similarityRouter);
apiRouter.use("/discovered-leads", discoveredLeadsRouter);
apiRouter.use("/audit", auditRouter);
apiRouter.use("/ai-usage", aiUsageRouter);
apiRouter.use("/nurturing", nurturingRouter);
apiRouter.use("/organizations", organizationsRouter);
apiRouter.use("/tenants", tenantsRouter);
apiRouter.use("/public", publicRouter);
apiRouter.use("/knowledge-base", knowledgeBaseRouter);
